route:
  receiver: 'Mail Alert'
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - to: '${ALERT_EMAIL}'
        from: '${SMTP_FROM}'
        smarthost: '${SMTP_SMARTHOST}'
        auth_username: '${SMTP_USER}'
        auth_password: '${SMTP_PASS}'
        auth_identity: '${SMTP_FROM}'
        headers:
          subject: 'Alerta Prometheus'
